name: CratesPlus
description: ${description}
main: plus.crates.CratesPlus
version: ${version}
api-version: '1.21.11'
author: Connor Linfoot
commands:
  crate:
    description: Main CratesPlus command
    aliases: [cratesplus,crates]
permissions:
  cratesplus.admin:
    default: op
  cratesplus.updates:
    default: op
